<<<<<<< HEAD
name: Mover estrutura do Flip App
=======
name: Preparar estrutura do Flip
>>>>>>> 067bda52fe94dc0dcb546eab99125f54ee26f7c6

on:
  workflow_dispatch:

jobs:
  reorganizar:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout do repositório completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verificar se a pasta tools/source existe
        run: |
          echo "📦 Verificando pasta tools/source..."
          if [ ! -d tools/source ]; then
            echo "❌ tools/source não encontrada. Aborto."
            exit 1
          fi
          if [ ! -f tools/source/package.json ]; then
            echo "❌ Nenhum Flip App válido em tools/source. Falta o package.json"
            exit 1
          fi
=======
      - name: Checkout do repositório com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # garante acesso ao histórico completo e arquivos versionados

      - name: Baixar arquivos grandes (Git LFS)
        run: git lfs pull || echo "sem arquivos LFS, seguindo..."

      - name: Verificar existência do zip
        run: |
          if [ ! -f ./tools/flip-agentos.zip ]; then
            echo "❌ Arquivo ./tools/flip-agentos.zip não encontrado!"
            exit 1
          fi

      - name: Extrair Flip App para /flip
        run: unzip -o ./tools/flip-agentos.zip -d flip
>>>>>>> 067bda52fe94dc0dcb546eab99125f54ee26f7c6

      - name: Verificar se a pasta /flip já existe
        run: |
          if [ -d flip ]; then
            echo "⚠️ A pasta /flip já existe. Abortando para evitar sobrescrita."
            exit 1
          fi

      - name: Mover conteúdo de tools/source para flip/
        run: |
          echo "🚚 Movendo arquivos..."
          mkdir flip
          mv tools/source/* flip/
          mv tools/source/src flip/src

      - name: Limpar lixo antigo (zip ou source)
        run: |
          echo "🧹 Limpando tools/"
          rm -rf tools/source tools/flip-agentos.zip || true

      - name: Commitar reorganização
        run: |
          git config user.name "agentos-auto-bot"
          git config user.email "infra@voulezvous.system"
          git add flip tools || echo "nada a adicionar"
          git diff --cached --quiet && echo '🔸 Nada mudou.' || git commit -m "infra: reorganiza estrutura do Flip App para /flip"
          git push