name: Preparar estrutura do Flip

on:
  workflow_dispatch:

jobs:
  preparar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # garante acesso ao histórico completo e arquivos versionados

      - name: Baixar arquivos grandes (Git LFS)
        run: git lfs pull || echo "sem arquivos LFS, seguindo..."

      - name: Verificar existência do zip
        run: |
          if [ ! -f ./tools/flip-agentos.zip ]; then
            echo "❌ Arquivo ./tools/flip-agentos.zip não encontrado!"
            exit 1
          fi

      - name: Extrair Flip App para /flip
        run: unzip -o ./tools/flip-agentos.zip -d flip

      - name: Comitar pasta /flip no repositório
        run: |
          git config user.name "agentos-flip-bot"
          git config user.email "infra@voulezvous.system"
          git add flip
          git commit -m "infra: estrutura inicial do Flip App automatizada"
          git push
